### ISSUE TITLE
How to download the app?

### ISSUE THREAD

**Issue by esperanza730** [benwithjamin/Derailleur#2]
Hello!

I was so excited to find this app! But I can’t seem to open it. Help! I’ve downloaded the zip file on my Apple SE phone, but what do I do next?

Thanks so much,
Hope

**Comment by benwithjamin** [comment]
Hi Hope,

Unfortunately this is not an iPhone app, so you won’t be able to use it on
your iPhone. It only works on macOS.

Ben

**Comment by esperanza730** [comment]
Got it. Thanks for the quick response! 😊
