### ISSUE TITLE
Anyway to work it with older MacOS?

### ISSUE THREAD

**Issue by rmaster78** [benwithjamin/Derailleur#4]
Was using MacOS 10.15 (Catalina), but don't have that laptop no more.  My old laptop can only run up to 10.11 or 10.12.  I am wondering if there is a way to make this work on the older macbook.

**Comment by benwithjamin** [comment]
Let's see - I've compiled this targeting macOS 10.11. There's only one thing in the code that wasn't available in 10.11, so I've tried to safely replace it (dark mode didn't exist back then and I've forcibly made my app dark). Let me know if it looks weird and I'll see if I can figure it out.
[Derailleur.zip](https://github.com/benwithjamin/Derailleur/files/5092929/Derailleur.zip)

**Comment by rmaster78** [comment]
thanks for the quick response.  that worked!!! back on again!

**Comment by rmaster78** [comment]
Closing as it is working!
