### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by rl0126** [benwithjamin/Derailleur#5]
Hiiii! Any chance you can offer guidance to help this not crash/app won't open? Using Catalina 10.15.6. THANK YOU so much!

**Comment by benwithjamin** [comment]
Do me a favour - when it happens can you click Send to Apple and screenshot
the information it gives you? Unfortunately I don’t have enough information
to help at the moment!

**Comment by rl0126** [comment]
Process:               Derailleur [20074]
Path:                  /private/var/folders/*/Derailleur.app/Contents/MacOS/Derailleur
Identifier:            com.benwithjamin.derailleur
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Derailleur [20074]
User ID:               501

Date/Time:             2020-10-31 14:21:00.267 -0500
OS Version:            Mac OS X 10.15.6 (19G2021)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010cb21000-000000010cb29000 [   32K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x0000000119fab000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee30deb28
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000119fab000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10cb21000 -        0x10cb28ff3 +??? (0) <2E8D31FC-F4F0-38F6-9B4A-8CAF1A4E16B6> (null)
       0x119faa000 -        0x11a03bf47 +??? (750.6) <F9D4DEDC-8296-3E3F-B517-9C8B89A4C094> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 757726
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=864K resident=0K(0%) swapped_out_or_unallocated=864K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             228K        3 
__DATA_CONST                        24K        2 
__LINKEDIT                         248K        2 
__TEXT                             616K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.1M       13 


This is using the "Latest" zip.

**Comment by rl0126** [comment]
Screen shot showing with the other one you've posted in the other issues that have now been closed!
![Screen Shot 2020-10-31 at 2 22 32 PM](https://user-images.githubusercontent.com/73757193/97788142-9e46b880-1b84-11eb-92a0-13b57fbfa556.png)

**Comment by benwithjamin** [comment]
[Derailleur.zip](https://github.com/benwithjamin/Derailleur/files/5477921/Derailleur.zip)

Does this work? If so, I'll make this the new release. I think I forgot to release it after I fixed it before!

**Comment by rl0126** [comment]
Yes it does - wow thank you!
