### ISSUE TITLE
Downloading on iPhone

### ISSUE THREAD

**Issue by jklmatthews** [benwithjamin/Derailleur#6]
Hi there- can you please help with how to download on an iPhone?

**Comment by benwithjamin** [comment]
You can’t. It’s a macOS app.

**Comment by jklmatthews** [comment]
Are you still able to log into your flywheel bike? I used to be able to and use Free Ride to get resistance and cadence but a few weeks ago I am now locked out.

**Comment by jklmatthews** [comment]
Does this app for Mac work regardless of logging in?

**Comment by benwithjamin** [comment]
Yeah you should be able to connect to Bluetooth without having to log in.
It just shows you the cadence and resistance - it’s only very basic but
hopefully means the bike is not just a worthless piece of kit!

**Comment by jklmatthews** [comment]
As long as I can still get into resistance and cadence! Will try now.

**Comment by jklmatthews** [comment]
You might have to make as phone app next ;)

**Comment by benwithjamin** [comment]
Haha I would but it’s $99 a year just to get stuff in the App Store! I can
make one but it would be hard to distribute

**Comment by jklmatthews** [comment]
Did you figure out a way to download this into the tablet that is on the bike?

**Comment by benwithjamin** [comment]
Unfortunately not. I don't have a bike with a tablet on it, but this app is
macOS only, so it wouldn't work anyway.

**Comment by jklmatthews** [comment]
Thoughts on what to do with this error once I downloaded the zip file and tried to open?

“Derailleur” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

**Comment by benwithjamin** [comment]
Unless you’re running macOS Big Sur, which I haven’t tested yet, you should
be able to right click and open that way. Many people ask this question. I
should include it in the readme.

**Comment by jklmatthews** [comment]
I just figured it out! Awesome it works! Wish it was on a phone so I didnt
have my computer propped up, but appreciate your work!

**Comment by JayNNNN** [comment]
I cannot use it. it does no open. I get the same error message. can you help?

**Comment by benwithjamin** [comment]
Right click the icon, click open, a dialog will open asking you to confirm
if you want to open the app.

**Comment by JayNNNN** [comment]
It is now working but it does not locate the bike and im moving the pedals. checked batteries...

**Comment by jklmatthews** [comment]
Have you ever thought of also adding "output" to it? The way that peleton
and flywheel measure your score?

**Comment by JayNNNN** [comment]
what do you mean by output?

**Comment by benwithjamin** [comment]
Is it a new bike/have you used it yet? If not, you’ll need to go to the
Bike menu and click connect. It should prompt you to calibrate the bike?
Are there any errors showing? In that menu you can also turn on debug mode
and send the output here so I can try to diagnose.

**Comment by benwithjamin** [comment]
Yeah the problem is that their calculations are (I think) proprietary. That
said, I can take a look again. I know someone has been adding some export
functionality to their own version but not sure how far they got.

**Comment by JayNNNN** [comment]
I bought it used. It does not have the monitor with it. it is the just the flywheel bike...

**Comment by JayNNNN** [comment]
it is working now.

**Comment by JayNNNN** [comment]
This would be great on an iOS app

**Comment by JayNNNN** [comment]
I just hope that the bike is calibrated correctly...

**Comment by cagnulein** [comment]
@benwithjamin @jklmatthews @JayNNNN i took your code and i insert it into my project https://github.com/cagnulein/qdomyos-zwift and it works flawlessy! so if you want you can use it on iOS.
I need some tester (i already know that it works with Flywheel 1, but i don't know for other type of bykes. So if you want to try it out, just write me your icloud account email to roberto.viola83@gmail.com and i add you on test flight for free.

I hope you will enjoy it!

**Comment by jklmatthews** [comment]
Jklaedtke@gmail.com is my email. Excited to try it!

**Comment by cagnulein** [comment]
@jklmatthews done, we have to wait apple. It's reviewing the beta. In the meanwhile you could join the FB group https://www.facebook.com/groups/149984563348738/

**Comment by jklmatthews** [comment]
Thank you! Does it work to connect into the Peleton app while using the Flywheel bike?

**Comment by cagnulein** [comment]
yes, of course!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 gen 2021 alle ore 20:18 jklmatthews <
notifications@github.com> ha scritto:

**Comment by JayNNNN** [comment]
I just downloaded the iOS version and it is not working. Bluetooth is connecting to the bike (flywheel) . Note that derailleur on Mac is able to identify the bike...

**Comment by JayNNNN** [comment]
Jair.Nunes.neves@gmail.com

**Comment by cagnulein** [comment]
The production version doesn't have the flywheel support yet. The version
for flywheel is in test flight ;)

Il mar 19 gen 2021, 00:49 JayNNNN <notifications@github.com> ha scritto:

**Comment by jklmatthews** [comment]
Would be great to know when Flywheel is up and running since I have a
flywheel bike and am currently using the Mac version.

**Comment by cagnulein** [comment]
Write me to roberto.viola83@gmail.com and i will add to test flight if you want to test it! @jklmatthews

**Comment by jklmatthews** [comment]
jklaedtke@gmail.com

**Comment by cagnulein** [comment]
done, check your email. wait the version 2.2.4 for the bug fixing ;)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 gen 2021 alle ore 07:28 jklmatthews <
notifications@github.com> ha scritto:

**Comment by jklmatthews** [comment]
I tried it and it worked great! A few comments:

- It did not let me click "start" or "stop", so the timer never turned on.
- The peloton output never calculated anything.
- I'd recommend putting the resistance and cadence next to each other since
these are the two things that all cycling classes focus on. Right now
cadence is top right and resistance is a few rows down on the left.

Thank you again for your work on this!

**Comment by cagnulein** [comment]
> - It did not let me click "start" or "stop", so the timer never turned on.

yes in that version they are only for treadmills. I'm developing the use of start and stop button even for the bike, start and stopping the recording session

> - The peloton output never calculated anything.

yes, i need a conversion from you. Because i don't know which is the conversion table with your bike. Could you provide me it?

> - I'd recommend putting the resistance and cadence next to each other since these are the two things that all cycling classes focus on. Right now cadence is top right and resistance is a few rows down on the left.

you can customize the tiles in the settings ;)
